//login
export const LOGIN_POPUP_OPEN = 'LOGIN_POPUP_OPEN';
export const LOGIN_POPUP_CLOSE = 'LOGIN_POPUP_CLOSE';
export const SIGNUP_POPUP_OPEN = 'SIGNUP_POPUP_OPEN';
export const SIGNUP_POPUP_CLOSE = 'SIGNUP_POPUP_CLOSE';

