/* COMMON */
export const MESSAGE_SHOW = 'MESSAGE_SHOW';
export const MESSAGE_HIDE = 'MESSAGE_HIDE';
export const MESSAGE_SHOW_DISMISSIBLE = 'MESSAGE_SHOW_DISMISSIBLE';

/* AUTH */
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_GOOGLE_USER = 'LOGIN_GOOGLE_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'LOGIN_USER_ERROR';
export const IS_AUTH = 'IS_AUTH';
export const IS_AUTH_SUCCESS = 'IS_AUTH_SUCCESS';
export const IS_AUTH_ERROR = 'IS_AUTH_ERROR';
export const REGISTER_USER = 'REGISTER_USER';
export const EMAIL_RESEND = 'EMAIL_RESEND';
export const PASSWORD_RESET = 'PASSWORD_RESET';
export const PASSWORD_RESET_SUCCESS = 'PASSWORD_RESET_SUCCESS';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const LOGOUT_USER = 'LOGOUT_USER';

/* SETTINGS */
export const SETTINGS_MODULES_LIST = 'SETTINGS_MODULES_LIST';

/* INTEGRATIONS */
export const GET_INTEGRATIONS = 'GET_INTEGRATIONS';
export const GET_INTEGRATIONS_SUCCESS = 'GET_INTEGRATIONS_SUCCESS';

/* MODALS */
export const OPEN_CONFIRM_MODAL = 'OPEN_CONFIRM_MODAL';
export const CLOSE_CONFIRM_MODAL = 'CLOSE_CONFIRM_MODAL';
export const OPEN_CONTENT_MODAL = 'OPEN_CONTENT_MODAL';
export const CLOSE_CONTENT_MODAL = 'CLOSE_CONTENT_MODAL';
export const EDIT_CONTENT_MODAL = 'EDIT_CONTENT_MODAL';
export const OPEN_ALERT_MODAL = 'OPEN_ALERT_MODAL';
export const CLOSE_ALERT_MODAL = 'CLOSE_ALERT_MODAL';

/* EMAIL DESIGN TEMPLATES */
export const GET_EMAIL_DESIGN_TEMPLATE = 'GET_EMAIL_DESIGN_TEMPLATE';
export const GET_EMAIL_DESIGN_TEMPLATE_SUCCESS = 'GET_EMAIL_DESIGN_TEMPLATE_SUCCESS';

/* BILLING */
export const GET_PAYMENTS_METHODS = 'GET_PAYMENTS_METHODS';
export const GET_PAYMENTS_METHODS_SUCCESS = 'GET_PAYMENTS_METHODS_SUCCESS';

export const ADD_PAYMENT_METHOD = 'ADD_PAYMENT_METHOD';
export const ADD_PAYMENT_METHOD_SUCCESS = 'ADD_PAYMENT_METHOD_SUCCESS';

export const REMOVE_PAYMENT_METHOD = 'REMOVE_PAYMENT_METHOD';
export const REMOVE_PAYMENT_METHOD_SUCCESS = 'REMOVE_PAYMENT_METHOD_SUCCESS';

export const SET_DEFAULT_CARD = 'SET_DEFAULT_CARD';
